apiVersion: apps/v1
kind: Deployment
#Defining metadata of the deployment using the image present in the docker hub
metadata:
  labels:
    app: flask-app
    version: 1.0
  name: flask-app
  namespace: flask-app
#It will use the default rolling update strategy and replica is 2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy: 
  #It uses the image from docker rajeev1391
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    #Deployment is named as flask-app
    spec:
      containers:
      - image: docker.io/rajeev1391/flask-app:1.0
        name: flask-app
        ports:
        - containerPort: 80
        resources: {}
status: {}