apiVersion: apps/v1
kind: deployment
#Defining metadata of the deployment using the image present in the docker hub
metadata:
  labels:
    app: flask-app
    version: "2.0"
    name: flask-app
#  namespace: default
  namespace: flask-app
#It will use the default rolling update strategy and replica is 2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy: 
  #It uses the image from docker rajeev1391
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    #Deployment is named as flask-app
    spec:
      containers:
      - image: docker.io/rajeev1391/flask-app:2.0
        name: flask-app
        ports:
        - containerPort: 80
        resources: {}
status: {}



#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: flask-app
#  labels:
#    app: flask-app
#spec:
#  type: LoadBalancer
#  selector:
#    app: flask-app
#  ports:
#    - port: 80
#      targetPort: 80
#      protocol: TCP