apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: d4c-cluster
  region: us-east-1

nodeGroups:
  - name: scale-spot
    desiredCapacity: 1
    maxSize: 2
    instancesDistribution:
      instanceTypes: ["t2.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    availabilityZones: ["us-east-1c", "us-east-1d"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateless-workload
      instance-type: spot
    ssh:
      publicKeyName: capstone

availabilityZones: ["us-east-1c", "us-east-1d"]
